//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPartsStockControlSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Item
    {
        [Required]
        public int ItemID { get; set; }
        [Required]
        public string ItemPart { get; set; }
        [RegularExpression("^[-_, A-Za-z]+$", ErrorMessage = "Please enter only Alphabetical Characters!")]
        public string ItemDescription { get; set; }
        public string ItemCategory { get; set; }
        [Required]
        public Nullable<int> ItemQuantity { get; set; }
        public Nullable<decimal> ItemPrice { get; set; }
        [RegularExpression("^[- A-Za-z]+$", ErrorMessage = "Please enter only Alphabetical Characters!")]
        public string VehicleMake { get; set; }
        [RegularExpression("^[- A-Za-z]+$", ErrorMessage = "Please enter only Alphabetical Characters!")]
        public string VehicleModel { get; set; }
        [RegularExpression("^[-_,0-9]*$", ErrorMessage = "Please enter only year Range! example:(2020-2021)")]
        public string VehicleModelYearRange { get; set; }
        public string PartCompatability { get; set; }
    }
}
