//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPartsStockControlSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemID { get; set; }
        public string ItemPart { get; set; }
        public string ItemDescription { get; set; }
        public string ItemCategory { get; set; }
        public Nullable<int> ItemQuantity { get; set; }
        public Nullable<decimal> ItemPrice { get; set; }
        public string VehicleMake { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleModelYearRange { get; set; }
        public string PartCompatability { get; set; }
    }
}
