//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPartsStockControlSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int SaleID { get; set; }
        public string ClientName { get; set; }
        public string ClientIDCard { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<int> SaleQuantity { get; set; }
        public string SalePart { get; set; }
        public string SaleDescription { get; set; }
    }
}
