//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPartsStockControlSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int SaleID { get; set; }
        public string ClientName { get; set; }
        public string ClientID { get; set; }
        public System.DateTime SaleDate { get; set; }
        public System.TimeSpan SaleTime { get; set; }
        public int ItemQuantitySold { get; set; }
        public string ItemCodeFK { get; set; }
        public string UserIDFK { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
    }
}
