//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPartsStockControlSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class StockOut
    {
        public int StockOutID { get; set; }
        [RegularExpression("^[-, A-Za-z]+$", ErrorMessage = "Please enter only Alphabetical Characters!")]
        public string ClientName { get; set; }
        [RegularExpression("^[-, A-Za-z]+$", ErrorMessage = "Please enter only Alphabetical Characters!")]
        public string ClientSurname { get; set; }
        public string ClientIDCard { get; set; }
        public string ClientContact { get; set; }
        public string StockOutPart { get; set; }
        public string StockOutDescription { get; set; }
        public Nullable<int> StockOutQuantity { get; set; }
        [DisplayFormat(ApplyFormatInEditMode =true, DataFormatString ="{0:dd-MM-yyyy}")]
        public string StockOutDate { get; set; }
    }
}
